teste/Controllers/AutenticacaoController.cs
using teste.Models;

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using System.Security.Claims;
using teste;
using teste.Utils;
using teste.DAO;

namespace teste.Controllers
{
    public class AutenticacaoController : Controller
    {
        private UsuariosContext db = new UsuariosContext();


        // GET: Autenticacao
        public ActionResult Cadastrar()
        {
            return View();
        }
         public ActionResult Cadastrar(CadastroUsuarioMetaDados viewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(viewModel);
    }
            if (db.Usuarios.Count(u =>u.Login  == viewModel.Login)>0)
            {
                ModelState.AddModelError("Login", "Esse Login ja existe");
                return View(viewModel);
              }
            Usuarios novoUsuario = new Usuarios
            {
            Nome = viewModel.Nome,
            Login = viewModel.Login,
            Senha = Hash.GerarHash(viewModel.Senha)
             };
             db.Usuarios.Add(novoUsuario);
            db.SaveChanges();
            TempData["Mensagem"] = "Cadastro realizado com sucesso";
            return View();
           
            
        }
        
       

    }
}

teste/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title </title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Cadastrar Login", "Cadastrar", "Autenticacao", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Meu Medico", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Medicos", "Index", "Medicos", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Especialidades", "Index", "Especialidades", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Cidades", "Index", "Cidades", new { area = "" }, new { @class = "navbar-brand" })


            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav"></ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer align="center">
            <p>&copy; @DateTime.Now.Year - Matheus Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <div class="lol"></div>
</body>
</html>