Logon/Controllers/PerfilController.cs
using Logon.Models;
using Logon.Utils;
using Logon.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;

namespace Logon.Controllers
{
    public class PerfilController : Controller
    {
        private UsuariosContext db = new UsuariosContext();

        [Authorize]
        public ActionResult AlterarSenha()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        public ActionResult AlterarSenha(AlterarSenhaViewModel viewmodel)
        {
            if (!ModelState.IsValid)
            {
                return View();

            }
            var identity = User.Identity as ClaimsIdentity;
            var login = identity.Claims.FirstOrDefault(c => c.Type == "Login").Value;
            var usuario = db.Usuarios.FirstOrDefault(u => u.Login == login);
            if (Hash.GerarHash(viewmodel.SenhaAtual) != usuario.Senha)
            {
                ModelState.AddModelError("SenhaAtual", "Senha Incorreta");
                return View();
            }
            usuario.Senha = Hash.GerarHash(viewmodel.NovaSenha);
            db.Entry(usuario).State = System.Data.Entity.EntityState.Modified;
            db.SaveChanges();
            TempData["Mensagem"] = "Senha Alterada Com Sucesso";
            return RedirectToAction("Index", "Home");
        } } }

Logon/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title </title>
    
    
   
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("INICIO", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">




                    @if (User.Identity.IsAuthenticated)
                    {

                        @Html.ActionLink("Medicos", "Index", "Medicos", new { area = "" }, new { @class = "navbar-brand" })
                        @Html.ActionLink("Especialidades", "Index", "Especialidades", new { area = "" }, new { @class = "navbar-brand" })
                        @Html.ActionLink("Cidades", "Index", "Cidades", new { area = "" }, new { @class = "navbar-brand" })
                        @Html.ActionLink("Estados", "Index", "Estados", new { area = "" }, new { @class = "navbar-brand" })

                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle"
                               data-toggle="dropdown">
                                @User.Identity.Name<span class="caret"></span>
                            </a>

                            <ul class=" dropdown-menu">



                                <li>@Html.ActionLink("Alterar Senha", "AlterarSenha", "Perfil")</li>
                                <li>@Html.ActionLink("Sair", "Logout", "Autenticacao")</li>
                            </ul>
                        </li>

                    }
                    else
                    {
                        <li>@Html.ActionLink("Cadastre-se", "Cadastrar", "Autenticacao")</li>
                        <li>@Html.ActionLink("Login", "Login", "Autenticacao")</li>
                    }


                </ul>
            </div>
        </div>
    </div>
   
    <div class="container body-content">
        
        @RenderBody()
        <hr />
        <footer>
            <div class="lol"></div>
            <p>&copy; @DateTime.Now.Year Matheus Application</p>
        </footer>
    </div>


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>